admins/urls.py
from django.urls import path
from django.views.i18n import set_language

from admins.views import UserListView, UserCreateView, UserUpdateView, UserDeleteView, CategoryListView, \
    CategoryCreateView, CategoryDeleteView, CategoryUpdateView, IndexTemplateView, ProductListView, ProductCreateView, \
    ProductDeleteView, ProductUpdateView

app_name = 'admins'

urlpatterns = [
    path('', IndexTemplateView.as_view(), name='index'),
    path('users/', UserListView.as_view(), name='admin_users'),
    path('users-create/', UserCreateView.as_view(), name='admin_users_create'),
    path('users-update/<int:pk>', UserUpdateView.as_view(), name='admin_users_update'),
    path('users-delete/<int:pk>', UserDeleteView.as_view(), name='admin_users_delete'),
    path('category/', CategoryListView.as_view(), name='admin_category'),
    path('category/create/', CategoryCreateView.as_view(), name='admin_category_create'),
    path('category-delete/<int:pk>/', CategoryDeleteView.as_view(), name='admin_category_delete'),
    path('category-update/<int:pk>/', CategoryUpdateView.as_view(), name='admin_category_update'),
    path('product/', ProductListView.as_view(), name='admin_product'),
    path('product/create/', ProductCreateView.as_view(), name='admin_product_create'),
    path('product-delete/<int:pk>/', ProductDeleteView.as_view(), name='admin_product_delete'),
    path('product-update/<int:pk>/', ProductUpdateView.as_view(), name='admin_product_update'),
    path('lang/', set_language, name='set_language'),
]

authapp/urls.py
from django.urls import path
from authapp.views import ProfileFormView, LoginListView, RegisterListView, Logout

app_name = 'authapp'
urlpatterns = [
    path('login/', LoginListView.as_view(), name='login'),
    path('register/', RegisterListView.as_view(), name='register'),
    path('profile/', ProfileFormView.as_view(), name='profile'),
    path('logout/', Logout.as_view(), name='logout'),
    path('verify/<str:email>/<str:activate_key>/', RegisterListView.verify, name='verify')
]

geekshop/urls.py
import debug_toolbar
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf.urls.static import static
from django.conf import settings

from mainapp.views import IndexTemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', IndexTemplateView.as_view(), name='index'),
    path('products/', include('mainapp.urls', namespace='mainapp')),
    path('users/', include('authapp.urls', namespace='authapp')),
    path('baskets/', include('baskets.urls', namespace='baskets')),
    path('admins/', include('admins.urls', namespace='admins')),
    path('', include('social_django.urls', namespace='social')),
    path('orders/', include('ordersapp.urls', namespace='orders')),
    path('i18n/', include('django.conf.urls.i18n')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += [path('debug/', include(debug_toolbar.urls))]

admins/templates/admins/admin-category-create.html
{% extends 'admins/base.html' %}
{% load static %}
{% block content %}
    <div id="layoutSidenav_content">
        <main>
            <div class="container-fluid">
                <h1 class="mt-4">Создание категории</h1>
                <form action="{% url 'admins:admin_category_create' %}" method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    <div class="form-row">
                        <div class="col-lg-6">
                            <div class="form-group">
                                <label class="small mb-1" for="{{ form.name.id_for_label }}">Название категории</label>
                                {{ form.name }}
                            </div>
                            <div class="form-group">
                                <label class="small mb-1" for="{{ form.description.id_for_label }}">Описание</label>
                                {{ form.description }}
                            </div>
                        </div>
                    </div>
                    <div class="form-row">
                        <div class="col-lg-12" style="margin-top: 33px;">
                            <input class="btn btn-info btn-block" type="submit" value="Сохранить">
                        </div>
                    </div>
                </form>
            </div>
        </main>
        <footer class="py-4 bg-light mt-auto">
            <div class="container-fluid">
                <div class="d-flex align-items-center justify-content-between small">
                    <div class="text-muted">Copyright &copy; GeekShop 2021</div>
                </div>
            </div>
        </footer>
    </div>
{% endblock %}

admins/templates/admins/admin-category-read.html
{% extends 'admins/base.html' %}
{% load static %}
{% block content %}
    <div id="layoutSidenav_content">
        <main>
            <div class="container-fluid">
                <h1 class="mt-4">Категории товаров</h1>
                <div class="card mb-4">
                    <div class="card-header">
                        <i class="fas fa-table mr-1"></i>
                        Категории
                    </div>
                    <div class="card-body">
                        <div class="table-responsive">

                            <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                                <thead>
                                <tr>
                                    <th>Имя категории</th>
                                    <th>Описание</th>
                                    <th>Активый</th>
                                    <th></th>
                                    <th></th>
                                </tr>
                                </thead>
                                <tbody>
                                {% for category in object_list %}
                                    <tr>
                                        <td><a href="{% url 'admins:admin_category_update' pk=category.id %}"
                                               style="color: dodgerblue">{{ category.name }}</a>
                                        </td>
                                        <td>{{ category.description }}</td>
                                        <td class="text-center">
                                            {% if category.is_active %}
                                                <i class="fas fa-check-circle"></i>
                                            {% else %}

                                                <i class="fas fa-times-circle"></i>
                                            {% endif %}
                                        </td>
                                        <td class="text-center">
                                            <a href="{% url 'admins:admin_category_update' pk=category.id %}">
                                                <input class="btn btn-lg btn-info" type="submit" value="Изменить">
                                            </a>
                                        </td>
                                        <td class="text-center">
                                            <form action="{% url 'admins:admin_category_delete' category.id %}"
                                                  method="post">
                                                {% csrf_token %}
                                                <input class="btn btn-lg btn-danger" type="submit" value="Удалить">
                                            </form>
                                        </td>
                                    </tr>
                                {% endfor %}
                                </tbody>
                            </table>
                        </div>
                    </div>
                    <div class="card-footer">
                        <a href="{% url 'admins:admin_category_create' %}">
                            <button class="btn btn-success">Создать категорию</button>
                        </a>
                    </div>
                </div>
            </div>
        </main>
        <footer class="py-4 bg-light mt-auto">
            <div class="container-fluid">
                <div class="d-flex align-items-center justify-content-between small">
                    <div class="text-muted">Copyright &copy; GeekShop 2021</div>
                </div>
            </div>
        </footer>
    </div>
{% endblock %}

admins/templates/admins/admin-category-update-delete.html
{% extends 'admins/base.html' %}
{% block content %}
    <div id="layoutSidenav_content">
        <main>
            <div class="container-fluid">
                <h1 class="mt-4">Редактирование категории | {{ productcategory.name }}  </h1>
                <div class="card-body">
                    <form action="{% url 'admins:admin_category_update' productcategory.id %}" method="post"
                          enctype="multipart/form-data">
                        {% csrf_token %}
                        <div class="form-row">
                            <div class="col-lg-6">
                                <div class="form-group">
                                    <label class="small mb-1" for="{{ form.name.id_for_label }}">Наименование</label>
                                    {{ form.name }}
                                </div>
                            </div>
                        </div>
                        <div class="form-row">
                            <div class="col-lg-6">
                                <div class="form-group">
                                    <label class="small mb-1" for="{{ form.discount.id_for_label }}">Скидка</label>
                                    {{ form.discount }}
                                </div>
                            </div>
                        </div>
                        <div class="form-row">
                            <div class="col-lg-6">
                                <div class="form-group">
                                    <label class="small mb-1" for="{{ form.description.id_for_label }}">Описание</label>
                                    {{ form.description }}
                                </div>
                            </div>
                        </div>
                        <div class="form-row">
                            <div class="col-lg-6" style="margin-top: 33px;">
                                <input class="btn btn-info btn-block" type="submit" value="Сохранить">
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </main>
        <footer class="py-4 bg-light mt-auto">
            <div class="container-fluid">
                <div class="d-flex align-items-center justify-content-between small">
                    <div class="text-muted">Copyright &copy; GeekShop 2021</div>
                </div>
            </div>
        </footer>
    </div>
{% endblock %}

admins/templates/admins/admin-product-create.html
{% extends 'admins/base.html' %}
{% load static %}
{% block content %}
    <div id="layoutSidenav_content">
        <main>
            <div class="container-fluid">
                <h1 class="mt-4">Создание товара</h1>
                <form action="{% url 'admins:admin_product_create' %}" method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    <div class="form-row">
                        <div class="col-lg-6">
                            <div class="form-group">
                                <label class="small mb-1" for="{{ form.name.id_for_label }}">Название продукта</label>
                                {{ form.name }}
                            </div>
                        </div>
                        <div class="col-lg-6">
                            <div class="form-group">
                                <label class="small mb-1"
                                       for="{{ form.short_description.id_for_label }}">Описание</label>
                                {{ form.short_description }}
                            </div>
                        </div>
                    </div>
                    <div class="form-row">
                        <div class="col-lg-6">
                            <div class="form-group">
                                <label class="small mb-1" for="{{ form.category.id_for_label }}">Категория</label>
                                {{ form.category }}
                            </div>
                        </div>
                        <div class="col-lg-6">
                            <div class="form-group">
                                <label class="small mb-1" for="{{ form.price.id_for_label }}">Цена</label>
                                {{ form.price }}
                            </div>
                        </div>
                    </div>
                    <div class="form-row mb-2">
                        <div class="col-lg-12">
                            <div class="custom-file">
                                {{ form.image }}
                                <label class="custom-file-label" for="{{ form.image.id_for_label }}">Выберите
                                    изображение</label>
                            </div>
                        </div>
                    </div>
                    <div class="form-row">
                        <div class="col-lg-12" style="margin-top: 33px;">
                            <input class="btn btn-info btn-block" type="submit" value="Сохранить">
                        </div>
                    </div>
                </form>
            </div>
        </main>
        <footer class="py-4 bg-light mt-auto">
            <div class="container-fluid">
                <div class="d-flex align-items-center justify-content-between small">
                    <div class="text-muted">Copyright &copy; GeekShop 2021</div>
                </div>
            </div>
        </footer>
    </div>
{% endblock %}

admins/templates/admins/admin-product-read.html
{% extends 'admins/base.html' %}
{% load static %}
{% block content %}
    <div id="layoutSidenav_content">
        <main>
            <div class="container-fluid">
                <h1 class="mt-4">Наименование товаров</h1>
                <div class="card mb-4">
                    <div class="card-header">
                        <i class="fas fa-table mr-1"></i>
                        Товары
                    </div>
                    <div class="card-body">
                        <div class="table-responsive">

                            <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                                <thead>
                                <tr>
                                    <th>Наименование</th>
                                    <th>Описание</th>
                                    <th>Категория</th>
                                    <th>Цена</th>
                                    <th>Количество</th>
                                    <th>Активный</th>
                                    <th></th>
                                    <th></th>
                                </tr>
                                </thead>
                                <tbody>
                                {% for product in object_list %}
                                    <tr>
                                        <td><a href="{% url 'admins:admin_product_update' pk=product.id %}"
                                               style="color: dodgerblue">{{ product.name }}</a></td>
                                        <td>{{ product.short_description }}</td>
                                        <td>{{ product.category }}</td>
                                        <td>{{ product.price }}</td>
                                        <td>{{ product.quantity }}</td>
                                        <td class="text-center">
                                            {% if product.is_active %}
                                                <i class="fas fa-check-circle"></i>
                                            {% else %}
                                                <i class="fas fa-times-circle"></i>
                                            {% endif %}
                                        </td>
                                        <td class="text-center">
                                            <a href="{% url 'admins:admin_product_update' pk=product.id %}">
                                                {% csrf_token %}
                                                <input class="btn btn-lg btn-info" type="submit" value="Изменить">
                                            </a>
                                        </td>
                                        <td class="text-center">
                                            <form action="{% url 'admins:admin_product_delete' product.id %}"
                                                  method="post">
                                                {% csrf_token %}
                                                <input class="btn btn-lg btn-danger" type="submit" value="Удалить">
                                            </form>
                                        </td>
                                    </tr>
                                {% endfor %}
                                </tbody>
                            </table>
                        </div>
                    </div>
                    <div class="card-footer">
                        <a href="{% url 'admins:admin_product_create' %}">
                            <button class="btn btn-success">Создать товар</button>
                        </a>
                    </div>
                </div>
            </div>
        </main>
        <footer class="py-4 bg-light mt-auto">
            <div class="container-fluid">
                <div class="d-flex align-items-center justify-content-between small">
                    <div class="text-muted">Copyright &copy; GeekShop 2021</div>
                </div>
            </div>
        </footer>
    </div>
{% endblock %}

admins/templates/admins/admin-product-update-delete.html
{% extends 'admins/base.html' %}
{% load static %}
{% block content %}
    <div id="layoutSidenav_content">
        <main>
            <div class="container-fluid">
                <h1 class="mt-4">Редактирование продукта | {{ product.name }}  </h1>
                <div class="card-body">
                    <form action="{% url 'admins:admin_product_update' product.id %}" method="post"
                          enctype="multipart/form-data">
                        {% csrf_token %}
                        <div class="form-row">
                            <div class="col-lg-6">
                                <div class="form-group">
                                    <label class="small mb-1" for="{{ form.name.id_for_label }}">Наименование</label>
                                    {{ form.name }}
                                </div>
                            </div>
                            <div class="col-lg-6">
                                <div class="form-group">
                                    <label class="small mb-1"
                                           for="{{ form.short_description.id_for_label }}">Описание</label>
                                    {{ form.short_description }}
                                </div>
                            </div>
                        </div>
                        <div class="form-row">
                            <div class="col-lg-6">
                                <div class="form-group">
                                    <label class="small mb-1" for="{{ form.category.id_for_label }}">Категория</label>
                                    {{ form.category }}
                                </div>
                            </div>
                            <div class="col-lg-6">
                                <div class="form-group">
                                    <label class="small mb-1"
                                           for="{{ form.price.id_for_label }}">Цена</label>
                                    {{ form.price }}
                                </div>
                            </div>
                        </div>
                        <div class="form-row">
                            <div class="col-lg-6">
                                <div class="form-group">
                                    <label class="small mb-1" for="{{ form.quantity.id_for_label }}">Количество</label>
                                    {{ form.quantity }}
                                </div>
                            </div>
                        </div>
                        <div class="form-row mb-2">
                            <div class="col-lg-12">
                                <div class="custom-file">
                                    {{ form.image }}
                                    <label class="custom-file-label" for="{{ form.image.id_for_label }}">Выберите
                                        изображение</label>
                                </div>
                            </div>
                        </div>
                        <div class="form-row">
                            <div class="col-lg-12" style="margin-top: 33px;">
                                <input class="btn btn-info btn-block" type="submit" value="Сохранить">
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </main>
        <footer class="py-4 bg-light mt-auto">
            <div class="container-fluid">
                <div class="d-flex align-items-center justify-content-between small">
                    <div class="text-muted">Copyright &copy; GeekShop 2021</div>
                </div>
            </div>
        </footer>
    </div>
{% endblock %}

admins/templates/admins/admin-users-read.html
{% extends 'admins/base.html' %}
{% block content %}
    <div id="layoutSidenav_content">
        <main>
            <div class="container-fluid">
                <h1 class="mt-4">Пользователи</h1>
                <div class="card mb-4">
                    <div class="card-header">
                        <i class="fas fa-table mr-1"></i>
                        Пользователи
                    </div>
                    <div class="card-body">
                        <div class="table-responsive">
                            <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                                <thead>
                                <tr>
                                    <th>Имя пользователя</th>
                                    <th>Имя</th>
                                    <th>Фамилия</th>
                                    <th>Адрес эл. почты</th>
                                    <th>Персонал сайта</th>
                                    <th>Активный</th>
                                </tr>
                                </thead>

                                <tbody>
                                {% for user in object_list %}
                                    <tr>
                                        <td><a href="{% url 'admins:admin_users_update' user.id %}"
                                               style="color: dodgerblue">{{ user.username }}</a>
                                        </td>
                                        <td>{{ user.first_name }}</td>
                                        <td>{{ user.last_name }}</td>
                                        <td>{{ user.email }}</td>
                                        <td class="text-center">
                                            {% if user.is_staff %}
                                                <i class="fas fa-check-circle"></i>
                                            {% else %}
                                                <i class="fas fa-times-circle"></i>
                                            {% endif %}
                                        </td>
                                        <td class="text-center">
                                            {% if user.is_active %}
                                                <i class="fas fa-check-circle"></i>
                                            {% else %}
                                                <i class="fas fa-times-circle"></i>
                                            {% endif %}
                                        </td>
                                    </tr>
                                {% endfor %}
                                </tbody>
                            </table>
                        </div>
                    </div>
                    <div class="card-footer">
                        <a href="{% url 'admins:admin_users_create' %}">
                            <button class="btn btn-success">Создать пользователя</button>
                        </a>
                    </div>
                </div>
            </div>
        </main>
        <footer class="py-4 bg-light mt-auto">
            <div class="container-fluid">
                <div class="d-flex align-items-center justify-content-between small">
                    <div class="text-muted">Copyright &copy; GeekShop 2021</div>
                </div>
            </div>
        </footer>
    </div>
{% endblock %}

admins/templates/admins/admin-users-update-delete.html
{% extends 'admins/base.html' %}
{% block content %}
    <div id="layoutSidenav_content">
        <main>
            <div class="container-fluid">
                <h1 class="mt-4">Редактирование пользователя | {{ user.username }}</h1>
                <div class="card-body">
                    <form action="{% url 'admins:admin_users_update' user.id %}" method="post"
                          enctype="multipart/form-data">
                        {% csrf_token %}
                        <div class="form-row">
                            <div class="col-lg-6">
                                <div class="form-group">
                                    <label class="small mb-1" for="{{ form.first_name.id_for_label }}">Имя</label>
                                    {{ form.first_name }}
                                </div>
                            </div>
                            <div class="col-lg-6">
                                <div class="form-group">
                                    <label class="small mb-1" for="{{ form.last_name.id_for_label }}">Фамилия</label>
                                    {{ form.last_name }}
                                </div>
                            </div>
                        </div>
                        <div class="form-row mb-2">
                            <div class="col-lg-12">
                                <div class="custom-file">
                                    {{ form.image }}
                                    <label class="custom-file-label" for="{{ form.image.id_for_label }}">Выберите
                                        изображение</label>
                                </div>
                            </div>
                        </div>
                        <div class="form-row">
                            <div class="col-lg-6">
                                <label class="small mb-1" for="{{ form.username.id_for_label }}">Имя
                                    пользователя</label>
                                {{ form.username }}
                            </div>
                            <div class="col-lg-6">
                                <label class="small mb-1" for="{{ form.email.id_for_label }}">Адрес электронной
                                    почты</label>
                                {{ form.email }}
                            </div>
                            <div class="col-lg-2">
                                <label class="small mb-1" for="{{ form.age.id_for_label }}">Возраст</label>
                                {{ form.age }}
                            </div>
                        </div>
                        <div class="form-row">
                            <div class="col-lg-12" style="margin-top: 33px;">
                                <input class="btn btn-info btn-block" type="submit" value="Сохранить">
                            </div>
                        </div>
                    </form>
                    <form action="{% url 'admins:admin_users_delete' user.id %}" method="post">
                        {% csrf_token %}
                        <div class="row">
                            <div class="col-lg-12" style="margin-top: 33px;">
                                <input class="btn btn-danger btn-block" type="submit" value="Удалить">
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </main>
        <footer class="py-4 bg-light mt-auto">
            <div class="container-fluid">
                <div class="d-flex align-items-center justify-content-between small">
                    <div class="text-muted">Copyright &copy; GeekShop 2021</div>
                </div>
            </div>
        </footer>
    </div>
{% endblock %}

admins/templates/admins/admin.html
{% extends 'admins/base.html' %}
{% block content %}
    <div id="layoutSidenav_content">
        <main>
            <div class="container-fluid">
                <h1 class="mt-4">Административная панель</h1>

            </div>
        </main>
        <footer class="py-4 bg-light mt-auto">
            <div class="container-fluid">
                <div class="d-flex align-items-center justify-content-between small">
                    <div class="text-muted">Copyright &copy; GeekShop 2021</div>
                </div>
            </div>
        </footer>
    </div>
{% endblock %}